apiVersion: v1
description: Info crawler for ezgliding data (flights, airspace, airfields, etc)
name: crawler
version: 0.1.0
home: https://github.com/ezgliding
sources:
  - https://github.com/ezgliding/helm
